export const drivers = [
  { id: 1, name: "Max Verstappen", team: "Red Bull Racing" },
  { id: 2, name: "Sergio Pérez", team: "Red Bull Racing" },
  { id: 3, name: "Lewis Hamilton", team: "Mercedes" },
  { id: 4, name: "George Russell", team: "Mercedes" },
  { id: 5, name: "Charles Leclerc", team: "Ferrari" },
  { id: 6, name: "Carlos Sainz", team: "Ferrari" },
  { id: 7, name: "Lando Norris", team: "McLaren" },
  { id: 8, name: "Oscar Piastri", team: "McLaren" },
  { id: 9, name: "Esteban Ocon", team: "Alpine (Renault)" },
  { id: 10, name: "Pierre Gasly", team: "Alpine (Renault)" },
  { id: 11, name: "Kevin Magnussen", team: "Haas" },
  { id: 12, name: "Nico Hülkenberg", team: "Haas" },
  { id: 13, name: "Fernando Alonso", team: "Aston Martin" },
  { id: 14, name: "Lance Stroll", team: "Aston Martin" },
  { id: 15, name: "Yuki Tsunoda", team: "AlphaTauri" },
  { id: 16, name: "Daniel Ricciardo", team: "AlphaTauri" },
  { id: 17, name: "Alex Albon", team: "Williams" },
  { id: 18, name: "Logan Sargeant", team: "Williams" },
  { id: 19, name: "Valtteri Bottas", team: "Alfa Romeo" },
  { id: 20, name: "Zhou Guanyu", team: "Alfa Romeo" },
]